# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Oyku Arkan"
email: 'oa'
description: "I am a Ph.D. candidate at Rutgers Business School!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamigibbs.github.io/phantom" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: 'jamigibbs'
github_username: 'jamigibbs'
medium_username: 'blog.jamigibbs.com'

#header_pages:
#  - index.markdown
#  - Publications.markdown
#  - Resume.markdown
#  - Contact.markdown

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed
# theme: phantom # Uncomment once published to RubyGems

### Phantom settings
#footer_text: '© 2018 Jami Gibbs'
google_analytics: "UA-175323907-2" # Update with your own tracking ID
#admin_name: 'Jami Gibbs'
#enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/research', text: 'Research' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/cv', text: 'CV' }
  - { url: '/contact', text: 'Contact' }
